services:
  - type: web
    name: baseball-card-api
    rootDir: TC-APP
    env: docker
    plan: free
    buildCommand: docker build -t myservice .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: baseball-card-db
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

databases:
  - name: baseball-card-db
    plan: free
    databaseName: baseball_card
    user: baseball_user
